services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  mysql:
    image: mysql:8.0.30
    command: --max_allowed_packet=167772160 --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -udev -pdev -e 'select 1'"
      start_period: 2s
      interval: 2s
      retries: 10
